irrokeys/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

website/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    
    path('',views.home,name='home' ),
    path('about/',views.about,name='about' ),
    path('solutions/',views.solutions,name='solutions' ),
    path('contact/',views.contact,name='contact' ),
    path('news/',views.news,name='news' ),
]

website/models.py
from django.db import models

# Create your models here.

website/forms.py
from django import forms

# Create your forms here.
from captcha.fields import CaptchaField



class ContactForm(forms.Form):
	first_name = forms.CharField(max_length = 50)
	last_name = forms.CharField(max_length = 50)
	email_address = forms.EmailField(max_length = 150)
	phone_number = forms.CharField(max_length = 50)
	message = forms.CharField(widget = forms.Textarea, max_length = 2000)
	captcha = CaptchaField()

website/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
import requests

# Create your views here.

def home(request):
    return render(request,'website/home.html')

def about(request):
    return render(request,'website/about.html')

def solutions(request):
    return render(request,'website/solutions.html')

def news(request):
    return render(request,'website/news.html')

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            email_address = form.cleaned_data['email_address']
            response = requests.get("https://isitarealemail.com/api/email/validate",params = {'email': email_address})
            subject = "Website Inquiry"
            status = response.json()['status']
            if status == "valid": 
                body = {
                'first_name': form.cleaned_data['first_name'], 
                'last_name': form.cleaned_data['last_name'], 
                'email': form.cleaned_data['email_address'],
                'phone_number': form.cleaned_data['phone_number'],  
                'message':form.cleaned_data['message'], 
                }
                message = "\n".join(body.values())

                try:
                    send_mail(subject, message, 'sales@irrokeys.de', ['djebab.toufik@irrokeys.com','belkadi.adel@irrokeys.com']) 
                except BadHeaderError:
                    return HttpResponse('Invalid header found.')
                return redirect ("home")
            
            else :
                print('not a valid email')
        
    form = ContactForm()
    return render(request, "website/contact.html", {'form':form})

website/templates/website/about.html
{% extends "website/base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'website/about.css' %}">

<section class="content_c">
    <h1 data-aos="fade-up">Our story</h1>
    <p data-aos="fade-down-left">
        <strong><span >irro'</span>keys</strong> was created by two former colleagues, 
        a research professor and a research engineer. 
        With significant experience in the fields of 
        engineering and a solid theoretical and academic
        background, the two founders saw <strong><span >irro'</span>keys</strong> as 
        a research & development startup aspiring to creation 
        and continuous innovation in the fields of high tech 
        technologies.

    </p>

    <p data-aos="fade-down-right">
        <strong><span >irro'</span>keys</strong> is also designed to meet a real need 
        in industry and compagnies. In the era of digitization 
        and Industry 4.0, the demands and expectations in terms
        of productivity, performance, quality, portability, 
        accessibility and modularity are increasingly important.
        One of the priorities for <strong><span >irro'</span>keys</strong> is therefore 
        the support and monitoring of companies in this 
        adventure of convergence towards this industry of 
        the future.
    </p>
   
</section>

   <section class="content_c2">
    <h1 data-aos="fade-up">Our activity area</h1>
    <p data-aos="fade-down-right">
        Our team of developpers are currentely working on building the website for You 
        in order to have the best experience visiting our website

    </p>

    <p data-aos="fade-down-left">
        Thanks to the transversal skills of our teams 
        and collaborators, we offer at <br> <strong><span >irro'</span>keys</strong> support,
         partnerships, solutions and research & development 
         work in the fields of:
    </p>

    <div>
        <img data-aos="fade-right" src="{% static 'images/puc.svg'%}" alt="">
        <p data-aos="fade-right">
          Robotics and automation control:
        At <br><strong><span >irro'</span>keys</strong>,
         We offer for our partners, solutions and support 
         in innovative projects related to the implementation 
         of industrial robots. We are also involved 
         in developing a  specific control modules in relation 
         to the needs of our customers.
        </p>

        <div data-aos="fade-left">
            <img src="{% static 'images/irrorobt.svg'%}" alt="">
        </div>
    </div>

    <div>
        <img data-aos="fade-right" src="{% static 'images/puc.svg'%}" alt="">
        <p data-aos="fade-right">
            Diagnosis and Quality control:
            We offer at <strong><span >irro'</span>keys</strong> a personalized solutions
             allowing our partners to implement and/or improve 
             their diagnostic and fault detection modules in 
             their machines and production lines. We are mainly 
             specialized in free model methods based on data 
             processing. We also support our customers in the 
             implementation of quality control tools and strategies 
             in their processes and production systems.
        </p>
        <div>
            <img data-aos="fade-left" src="{% static 'images/irrodiag.svg'%}" alt="">
        </div>
    </div>

    <div>
        <img data-aos="fade-right" src="{% static 'images/puc.svg'%}" alt="">
        <p data-aos="fade-right">
            AI, Machine Learning & Data Science :
            The implementation of intelligent modules in 
            companies and industries is now becoming a necessity to 
            optimize and improve the performance of systems and processes.
             Our teams at <strong><span >irro'</span>keys</strong>  offer to support you in innovative projects involving 
             different skills in Artificial Intelligence, Machine Learning and Data Science.
        </p>
        <div>
            <img data-aos="fade-left" src="{% static 'images/irrosmart.svg'%}" alt="">
        </div>
    </div>

    <div>
        <img data-aos="fade-right" src="{% static 'images/puc.svg'%}" alt="">
        <p data-aos="fade-right">
            Apps Development and Software Solutions:
            Our <strong><span >irro'</span>keys</strong> teams offer to support you in your 
            digitalization process through the development of software 
            solutions, applications and HMI interfaces. Assuring our 
            partners a customized solution in line with their specificities 
            and their current needs.
        </p>
        <div data-aos="fade-left">
            <img src="{% static 'images/irroapp.svg'%}" alt="">
        </div>
    </div>

</section>

<section class="content_c3">
    <h1 data-aos="fade-down">Why choose <strong><span >irro'</span>keys</strong></h1>
    <div data-aos="flip-right">
        <div>
            	<img src="{% static 'images/customs.svg'%}" alt="">
                <h2>Customized solution</h2>
                <p>
                    <strong><span >irro'</span>keys</strong> offers an adapted and personalized solutions for partners taking into account their needs and specificities.
                </p>
        </div>
        <div>
            <img src="{% static 'images/expertise.svg'%}" alt="">
            <h2>Expertise</h2>
            <p>
                <strong><span >irro'</span>keys</strong> offers an adapted and personalized solutions
                 for partners taking into account their needs and specificities.
            </p>
    </div>
        
    </div>

    <div data-aos="flip-left">
        <div>
            <img src="{% static 'images/available.svg'%}" alt="">
                <h2>Availability & Responsiveness</h2>
                <p>
                    Our <strong><span >irro'</span>keys</strong> teams provide you with quality 
                    support by always being at your disposal to discuss
                     and find solutions in accordance with your current 
                     needs.                </p>
        </div>
        <div>
            <img src="{% static 'images/team.svg'%}" alt="">
                <h2>Commitment and teamwork</h2>
                <p>
                    Our <strong><span >irro'</span>keys</strong> tems will support your projects with a
                    strong commitment and a desire to always do better and 
                    go further.        
        </div>
    </div>

    <h1 data-aos="fade-down"><strong><span >irro'</span>keys</strong> team</h1>
    <p data-aos="fade-down">Our multidisciplinary <strong><span >irro'</span>keys</strong> team is formed by professionals 
        in the field of high tech (PhD, research engineers and software 
        developers). Thanks to their expertise and experience, our team 
        will provide you with excellent work and quality support in your 
        innovative projects, in order to guarantee you better profitability, 
        quality and efficiency.</p>
</section>

{% include 'website/founders.html' %}



<script type="text/javascript" src="{% static 'website/about.js' %}"> </script>  
{% endblock %}

website/templates/website/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.5 user-scalable=no">
    <!-- , user-scalable=no -->
  
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Poppins&display=swap');
            </style>

<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'website/base.css' %}">
    <title>irrokeys</title>
</head>
<body>
    <header >
    
                <svg onclick="location.href='/'"; href="{% url 'home' %}" id="Component_12_1" data-name="Component 12 – 1" xmlns="http://www.w3.org/2000/svg" width="316" height="85.531" viewBox="0 0 350 85.531">
                    <rect width="32%" height="62%" fill="#ffde59" preserveAspectRatio="none" y="-3" />
                      
                      <text id="irro_keys" data-name="irro keys" transform="translate(6 43)" fill="#fefefe" font-size="3.5rem" font-family="Poppins-Bold, Poppins" font-weight="900"><tspan x="0" y="2" fill="#000">irro</tspan><tspan y="2" x= "110" xml:space="preserve" fill="#fefefe">keys</tspan></text>
                      <text id="innovative_research_partner_in_new_technologies" data-name="innovative research partner in new technologies" transform="translate(0 55.531)" fill="#fff" font-size="12" font-family="Poppins-Bold, Poppins" font-weight="500"><tspan x="0" y="13">innovative research partner in new technologies</tspan></text>
                    </svg>
                    
                
                <span onclick="myFunction()" class="hamburger">
                    <div></div>
                    <div></div>
                    <div></div>
                    
                </span>
                
           <nav  class="buttons_c">
               <a href=""></a>
                <a onclick="location.href='/'"; href="{% url 'home' %}">Home</a>
                <a onclick="location.href='/about'"; href="{% url 'about' %}">About</a>
                <a onclick="location.href='/solutions'"; href="{% url 'solutions' %}">Solutions</a>
                <a onclick="location.href='/news'"; href="{% url 'news' %}">News</a>
                <a onclick="location.href='/contact'"; href="{% url 'contact' %}">Contact</a>  
                <a>Language</a>
                <a>Search</a>   
                
            </nav> 
            
            

        <div   class="nav_content">
           
                <h1 data-aos="fade-right">Your <span>irro'</span>keys Innovative Research Partner</h1>
                <h1 data-aos="fade-left">in new Technologies</h1>
        </div>
        
        
                <div class="but_div">
                 <button data-aos="fade-up-right" onclick="location.href='/about'"; href="{% url 'about' %}" class="big_b ">About us</button>
                <button data-aos="fade-up-left" onclick="location.href='https://www.linkedin.com/company/71269492'"; class="big_b ">Follow us</button>
                </div>
       

                <div id="links" class="ham_menu">
                  
                  <div> 
                    <div>
                      <svg onclick="location.href='/'"; href="{% url 'home' %}" id="Component_12_1" data-name="Component 12 – 1" xmlns="http://www.w3.org/2000/svg" width="316" height="85.531" viewBox="0 0 350 85.531">
                        <rect width="32%" height="62%" fill="#ffde59" preserveAspectRatio="none" y="-3" />
                          
                          <text id="irro_keys" data-name="irro keys" transform="translate(6 43)" fill="#fefefe" font-size="3.5rem" font-family="Poppins-Bold, Poppins" font-weight="900"><tspan x="0" y="2" fill="#000">irro</tspan><tspan y="2" x= "110" xml:space="preserve" fill="#fefefe">keys</tspan></text>
                          <text id="innovative_research_partner_in_new_technologies" data-name="innovative research partner in new technologies" transform="translate(0 55.531)" fill="#fff" font-size="12" font-family="Poppins-Bold, Poppins" font-weight="500"><tspan x="0" y="13">innovative research partner in new technologies</tspan></text>
                        </svg>
                      
                        <button onclick="close_menu()">&#x2715</button>
                    </div>
                    <a onclick="location.href='/'"; href="{% url 'home' %}">Home</a>
                    <a onclick="location.href='/about'"; href="{% url 'about' %}">About</a>
                    <a onclick="location.href='/solutions'"; href="{% url 'solutions' %}">Solutions</a>
                    <a onclick="location.href='/news'"; href="{% url 'news' %}">News</a>
                    <a onclick="location.href='/contact'"; href="{% url 'contact' %}">Contact</a>  
                    <a>Language</a>
                    <a>Search</a>  
                  </div>
                
                </div>
    

    
    </header>

    <div class="name_c" >
        <h1 id= "name_c"></h1>
    </div>

    <div style="width: 100vw; display: flex; padding-bottom: 5vh;" >
        
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="60" height="51" viewBox="0 0 60 51">
            <defs>
              <filter id="Polygon_8" x="0" y="0" width="60" height="51" filterUnits="userSpaceOnUse">
                <feOffset dy="3" input="SourceAlpha"/>
                <feGaussianBlur stdDeviation="3" result="blur"/>
                <feFlood flood-color="#121a41"/>
                <feComposite operator="in" in2="blur"/>
                <feComposite in="SourceGraphic"/>
              </filter>
            </defs>
            <g transform="matrix(1, 0, 0, 1, 0, 0)" filter="url(#Polygon_8)">
              <path id="Polygon_8-2" data-name="Polygon 8" d="M21,0,42,33H0Z" transform="translate(51 39) rotate(180)" fill="#ffde59"/>
            </g>
          </svg>
    </div>

    
    {% block content %}
    
    {% endblock %}
  
    
    <footer >
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 120"><path fill="#FFF" fill-opacity="1" d="M0,64L120,53.3C240,43,480,21,720,21.3C960,21,1200,43,1320,53.3L1440,64L1440,0L1320,0C1200,0,960,0,720,0C480,0,240,0,120,0L0,0Z"></path></svg>
        <div>
          <div>
            <svg onclick="location.href='/'"; href="{% url 'home' %}" id="Component_12_1" data-name="Component 12 – 1" xmlns="http://www.w3.org/2000/svg" width="316" height="85.531" viewBox="0 0 350 85.531">
              <rect width="32%" height="62%" fill="#ffde59" preserveAspectRatio="none" y="-3" />
                
                <text id="irro_keys" data-name="irro keys" transform="translate(6 43)" fill="#fefefe" font-size="3.5rem" font-family="Poppins-Bold, Poppins" font-weight="900"><tspan x="0" y="2" fill="#000">irro</tspan><tspan y="2" x= "110" xml:space="preserve" fill="#fefefe">keys</tspan></text>
                <text id="innovative_research_partner_in_new_technologies" data-name="innovative research partner in new technologies" transform="translate(0 55.531)" fill="#fff" font-size="12" font-family="Poppins-Bold, Poppins" font-weight="500"><tspan x="0" y="13">innovative research partner in new technologies</tspan></text>
              </svg>
              <p>djebab.toufik@irrokeys.de</p>
              <p>belkadi.adel@irrokeys.de</p>
              <p>sales@irrokeys.de</p>
          </div>
          <div>
            <p></p>
            <p></p>
            <p style="text-align: center;">Call us </p>
            <p>Germany : +49.152.560.167.75</p>
            
            <p>France : +33.9.83.52.29.14</p>
  
          </div>
          <div>
          
              <a onclick="location.href='/'"; href="{% url 'home' %}">Home</a>
                  <a onclick="location.href='/about'"; href="{% url 'about' %}">About</a>
                  <a onclick="location.href='/solutions'"; href="{% url 'solutions' %}">Solutions</a>
                  <a onclick="location.href='/news'"; href="{% url 'news' %}">News</a>
                  <a onclick="location.href='/contact'"; href="{% url 'contact' %}">Contact</a>  
          </div>
        </div>
    </footer>

    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
    AOS.init();
  </script>
    <script type="text/javascript" src="{% static 'website/base.js' %}"> </script>
</body>

</html>

website/templates/website/contact.html
{% extends "website/base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'website/contact.css' %}">
<section class="content_c">
    <div>
        <div data-aos="fade-up">
            <h1>Phone number</h1>
            <p>+49 152 560 167 75</p>
        </div>
    
    
        <div data-aos="fade-up-right">
            <h1>E-mails</h1>
            <p>djebab.toufik@irrokeys.com</p>
            <p>belkadi.adel@irrokeys.com</p>
            <p>sales@irrokeys.de</p>
        </div>
    </div>

    <div data-aos="fade-up-left">
        <h1><span>></span> Social media</h1>
        <a class="linkedin" target="_blank" href="https://www.linkedin.com/company/71269492"><img src="{% static 'images/LI-Logo.png' %}"   ></a>
    
    </div>

    <h1 data-aos="fade-down"> <span>></span> Contact us </h1>
    <p data-aos="fade-down">If you have any questions, please fill out the form below and we will answer you as soon as possible.</p>
    <form method="post" >
        {% csrf_token %}
        
        <div>
            
            <input placeholder="First name" onfocus="this.placeholder = ''"  type="text" name="first_name" maxlength="50" required="" id="id_first_name">
            <input placeholder="Last name" onfocus="this.placeholder = ''" type="text" name="last_name" maxlength="50" required="" id="id_last_name">
            <input placeholder="E-mail" onfocus="this.placeholder = ''" type="email" name="email_address" maxlength="150" required="" id="id_email_address">
            <input placeholder="Phone number" onfocus="this.placeholder = ''" type="text" name="phone_number" maxlength="150" required="" id="phone_number">
            {{ form.captcha }}
        </div>
            
            <textarea placeholder="Enter your text Here" onfocus="this.placeholder = ''" name="message" cols="40" rows="10" maxlength="2000" required="" id="id_message"></textarea>
            <button type="submit">Submit</button>
           
            <div> <input id ="consent" type="checkbox" required=""> <p>I have read and accepte <a href="https://www.privacypolicies.com/live/ce80813f-b6ed-4a54-aa62-bddf9b2438fb">the privacy policy</a></p></div>
    </form>
    
    
      
 </section>

 <script type="text/javascript" src="{% static 'website/contact.js' %}"> </script>  

{% endblock %}

website/templates/website/founders.html
{% load static %}
<link rel="stylesheet" href="{% static 'website/founders.css' %}">
<section class="content_c4">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#FFF" fill-opacity="1" d="M0,32L14.1,48C28.2,64,56,96,85,112C112.9,128,141,128,169,149.3C197.6,171,226,213,254,197.3C282.4,181,311,107,339,106.7C367.1,107,395,181,424,181.3C451.8,181,480,107,508,90.7C536.5,75,565,117,593,122.7C621.2,128,649,96,678,96C705.9,96,734,128,762,149.3C790.6,171,819,181,847,181.3C875.3,181,904,171,932,170.7C960,171,988,181,1016,197.3C1044.7,213,1073,235,1101,208C1129.4,181,1158,107,1186,90.7C1214.1,75,1242,117,1271,160C1298.8,203,1327,245,1355,240C1383.5,235,1412,181,1426,154.7L1440,128L1440,0L1425.9,0C1411.8,0,1384,0,1355,0C1327.1,0,1299,0,1271,0C1242.4,0,1214,0,1186,0C1157.6,0,1129,0,1101,0C1072.9,0,1045,0,1016,0C988.2,0,960,0,932,0C903.5,0,875,0,847,0C818.8,0,791,0,762,0C734.1,0,706,0,678,0C649.4,0,621,0,593,0C564.7,0,536,0,508,0C480,0,452,0,424,0C395.3,0,367,0,339,0C310.6,0,282,0,254,0C225.9,0,198,0,169,0C141.2,0,113,0,85,0C56.5,0,28,0,14,0L0,0Z"></path></svg>
    
    <h1 data-aos="flip-up"> <span >irro'</span>keys founders</h1>
    <div>
        <img data-aos="fade-down" class="founder1" src="{% static 'images/adel.png'%}" alt="">
        <img data-aos="fade-down" class="founder2" src="{% static 'images/toufik.png'%}" alt="">
        <div data-aos="fade-down" class="text1">
       
            <p>Adel BELKADI</p>
            <p>Co-founder</p>
            <p>Robotics, AI and data science</p>
            <p> belkadi.adel@irrokeys.com</p>
            <p>"Your satisfaction is our goal and your imagination is our limit".</p>
        </div>
      
        <div data-aos="fade-down" class="text2">
          
            
            <p>Djebab Toufik</p>
            <p>Co-founder</p>
            <p>Automation and system design</p>
            <p> djebab.toufik@irrokeys.com</p>
            <p>"We think about things and innovate"</p>
        </div>
    </div>

   
    
  
   <svg  xmlns="http://www.w3.org/2000/svg"   viewBox="0 0 1440 320"><path transform="translate(0 43)" fill="#FFF" fill-opacity="1" d="M0,256L80,240C160,224,320,192,480,192C640,192,800,224,960,234.7C1120,245,1280,235,1360,229.3L1440,224L1440,320L1360,320C1280,320,1120,320,960,320C800,320,640,320,480,320C320,320,160,320,80,320L0,320Z"></path></svg>
    
</section>

website/templates/website/home.html
{% extends "website/base.html" %}
{% load static %}

{% block content %}
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'website/home.css' %}">
<div  class="content_c">

    
        
    <h1 > <strong><span >irro'</span>keys</strong> in few words</h1>
     
    <p data-aos="fade-up-right">
        <strong><span >irro'</span>keys</strong> is a research & development startup in high tech technologies. Our main objective is 
    to provide and offer our partners innovative technological solutions in line with market and companies needs.
    </p>

    <p data-aos="fade-up-left">
        Our multidisciplinary teams, made up of phds, research engineers and software developers, will guarantee an excellent 
        work to ensure better profitability, quality and efficiency for our partners.
    
    </p>

  
    
    
    


<button data-aos="flip-left" onclick="location.href='/solutions'"; href="{% url 'solutions' %}" class="learn_more">Learn more +</button>   
</div>

<div class="content_c2">
    <h1 data-aos="flip-up">Our expertise area</h1>
    
        
        <p data-aos="zoom-in">
            We mainly work at <strong><span>irro'</span>keys</strong> to develop technological solutions in relation to the needs of industry and companies in general. 
           <br> Thanks to the transversal skills of our collaborators, we offer research & development work in the fields of:
            
        </p>
       
        
       <div data-aos="zoom-in-up" >
        <img data-aos="fade-right" src= "{% static 'images/puc.svg' %}" alt=""> 
            <p>
                 Industrial Robotics; Diagnosis; Fault Detection & Isolation; Supervision & Quality Control.
                
            </p>

       </div>
        
      <div data-aos="zoom-in-up">

        <img img data-aos="fade-right" src= "{% static 'images/puc.svg' %}" alt="">
        <p>
              Artificial Intelligence & Machine Learning; Data Mining & Data Analysis.
            
        </p>
      </div>

      <div data-aos="zoom-in-up">
        <img src= "{% static 'images/puc.svg' %}" alt="">
        <p img data-aos="fade-right">
               Apps Development and Software Solutions for Industrial Applications
            
        </p>
      </div>
    
</div>

<div class="content_c3">

    <div data-aos="fade-right" class="image_c">
    <img src="{% static 'images/irrorobt.svg' %}" alt="">
    </div>

    <div data-aos="fade-left" class="image_c">
        <img src="{% static 'images/irrodiag.svg' %}" alt="">
    </div>

    <div data-aos="fade-down" class="image_c">
        <img src="{% static 'images/irrosmart.svg' %}" alt="">
    </div>

    <div data-aos="fade-down" class="image_c">
        <img src="{% static 'images/irroapp.svg' %}" alt="">
    </div>
    

</div>

<div style="display: flex; width: 100vw;">
    <button onclick="location.href='/solutions'"; href="{% url 'solutions' %}" data-aos="flip-right" class="learn_more">Learn more +</button>
</div>

   
{% include 'website/founders.html' %}

<section class="svgdown">
  
    
    <div style="display: flex; padding-bottom: 7vh;">
        <button data-aos="flip-down" onclick="location.href='/contact'"; href="{% url 'contact' %}" class="learn_more bigger">Contact us for more information</button> 
      </div>
</section>

<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
    AOS.init();
  </script>
  <script type="text/javascript" src="{% static 'website/home.js' %}"> </script>  



{% endblock %}

website/templates/website/solutions.html
{% extends "website/base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'website/solutions.css' %}">
<section class="content_c">
    <h1 data-aos="fade-down">Our solutions</h1>
    <p data-aos="fade-down">
        At <strong><span >irro'</span>keys</strong>, we develop and offer software and 
        hardware solutions in the fields of robotics, automation, 
        AI, data processing, diagnostics and quality control).

    </p>
    <h1 data-aos="fade-up">Current projects</h1>
    <div>
        <img data-aos="fade-up" src="{% static 'images/qualitex.svg' %}" alt="">
        <img data-aos="fade-up" src="{% static 'images/iotex.svg' %}" alt="">
        <img data-aos="fade-up" src="{% static 'images/erp.svg' %}" alt="">
    </div>
    <h1 data-aos="fade-up">Our latest projects and experiences</h1>
    <div class="slider">
       <figure>
        <img src="{% static 'images/autocontrol.png' %}" alt="">
        <img src="{% static 'images/diagfaul.png' %}" alt="">
        <img src="{% static 'images/multiagent.png' %}" alt="">
        <img src="{% static 'images/production.png' %}" alt="">
        <img src="{% static 'images/grilling.png' %}" alt="">
       </figure>
    </div>
    <button onclick="location.href='/contact'"; href="{% url 'contact' %}" class="learn_more">Contact us for more information</button>
   
</section>

<script type="text/javascript" src="{% static 'website/solutions.js' %}"> </script>  
{% endblock %}